---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
    ms: '{{ ms }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u shsdocuments5@gmail.com -p Hiqode@123 hiqode.jfrog.io  
    
    - name: pull an image
      shell: docker pull hiqode.jfrog.io/cicd-docker-docker-local/app-a/{{ ms }}:{{ build_number }}

   # - name: remove container
    #  shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 hiqode.jfrog.io/cicd-docker-docker-local/app-a/{{ ms }}:{{ build_number }}
 
   
